from examples_tts.fastspeech2.fastspeech2_dataset import CharactorDurationF0EnergyMelDataset
from examples_tts.fastspeech.train_fastspeech import FastSpeechTrainer
from examples.fastspeech.fastspeech_dataset import CharactorDataset
